### ISSUE TITLE
Make a list of interested developers in GraphQL over HTTP

### ISSUE THREAD

**Issue by deinok** [APIs-guru/graphql-over-http#1]
Library developers can miss the efforts of developing a spec of GraphQL over HTTP.
It's important that in order to have interoperability over diferent programing languages or frameworks the developers of this libraries know about this, so they can explain pros and const of every decision made here.

I propose the creation of a file called INTERESTED_DEVELOPERS.md that track:
- Programing Language
- Frameworks (If have sense)
- GitHub User
- Point of View
- Main Repository

As an example (of myself):
- .NET
- graphql-dotnet
- @Deinok
- CLIENT
- https://github.com/graphql-dotnet/graphql-client

**Comment by mike-marcacci** [comment]
Please add myself and @jaydenseric who has created the [graphql multipart spec](https://github.com/jaydenseric/graphql-multipart-request-spec)
