### ISSUE TITLE
spaces in url query strings

### ISSUE THREAD

**Issue by jiaming2012** [APIs-guru/graphql-over-http#3]
In your GET example, the space in ($id: ID!) invalidates the request.
```
http://example.com/graphql?query=query($id: ID!){user(id:$id){name}}&variables={"id":"QVBJcy5ndXJ1"}
```
Do you recommend clients implementing a graphql api remove all spaces in queries or url encode the query string. For example:
```
url = 'http://example.com/graphql?query=' + quote('query($id: ID!){user(id:$id){name}}&variables={"id":"QVBJcy5ndXJ1"}')
```

**Comment by IvanGoncharov** [comment]
@jiaming2012 Definitely URL encoded.
You can have space and any other symbols inside argument strings
```graphql
{
  user(name: "Ivan Goncharov")
}
```

I'm keeping this issue since it definetly should be addressed in spec text.

**Comment by IvanGoncharov** [comment]
@benjie You mentioned it #6 
Do you want to work on PR to address this in spec text?

**Comment by benjie** [comment]
I’ll give it a go 👍 Might be a few days.
