### ISSUE TITLE
Dec 17 GraphQL-over-HTTP working group meeting

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#46]
Hello, just opening a discussion to remind interested devs about our working group meeting Dec 17th. Please see the agenda and open a PR to add yourself:

https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2019-12-17.md

@benjie @deinok @erikwittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @IvanGoncharov

**Comment by spawnia** [comment]
Inviting @vladar and @mfn to join.
