### ISSUE TITLE
Jan 28 GraphQL-over-HTTP working group meeting

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#62]
Hello, just opening a discussion to remind interested devs about our working group meeting on Jan 28th. Please see the agenda and open a PR to add yourself:

https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-01-28.md

@abernix @balshor @benjie @deinok @erikwittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @spawnia @sungam3r

**Comment by benjie** [comment]
I'm afraid I can't make it to this one; looking forward to reading over the notes though!

**Comment by abernix** [comment]
I will be unable to attend this meeting.  @trevor-scheer is still attending from the Apollo team, however.

As an update on the feature/capabilities matrix action item I am responsible for: I have not been able to get to this just yet, but still intend to get to it ASAP, presumably before the February meeting.

**Comment by sjparsons** [comment]
Sorry you can't come @benjie and @abernix!

**Comment by balshor** [comment]
Thanks for the ping -- I unfortunately can't make it today.  Hope to meet you all next month, though!

**Comment by spawnia** [comment]
Thanks @sjparsons, can't make it.

Maybe you can ask what everyone thinks about https://github.com/APIs-guru/graphql-over-http/issues/57
