### ISSUE TITLE
Actions from Feb 25 meeting

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#69]
Based on the meeting today, here's the planned actions we'd like to work on next. If you're tagged here and you feel you cannot meet that commitment, please comment or DM me. Also, if you'd like to get involved on any of these actions just post.

Planned before next meeting:

- [x] @sjparsons - List of tests that we should implement
- [x] @benjie  - Raise an issue or PR to add a User-Agent header to the client running the tests
- [x] @jaydenseric  - rename and publish `graphql-http-test`
- [ ] @IvanGoncharov - Provide one sentence mission statement
- [ ] @IvanGoncharov - Add paragraph/sentence explaining the state of the project legally migrating to GraphQL
 
See [agenda](https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-02-25.md) for notes and more details.

**Comment by benjie** [comment]
@sjparsons You can cross off my task: https://github.com/jaydenseric/test-graphql-http/issues/2

**Comment by sjparsons** [comment]
@benjie I was hoping that you could check the boxes, but perhaps you don't have rights :(

**Comment by benjie** [comment]
Yeah; I tried :disappointed:

**Comment by jaydenseric** [comment]
My action item can be crossed off, `graphql-http-test` has been published:

- https://github.com/jaydenseric/graphql-http-test/releases/tag/v1.0.0-alpha.1
- https://www.npmjs.com/package/graphql-http-test

@benjie 's good idea about the user agent header has also been actioned:

- https://github.com/jaydenseric/graphql-http-test/issues/2
- https://github.com/jaydenseric/graphql-http-test/commit/95caf5f883d62ac74184b93989bf54a09776027f

**Comment by sjparsons** [comment]
Have added a PR with a proposed list of tests we could implement.
