### ISSUE TITLE
Mar 24 working group meeting

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#71]
Hello, just opening a discussion to remind interested devs about our working group meeting on Mar 24th. Please see the agenda and open a PR to add yourself:

https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-03-24.md

@abernix @balshor @benjie @deinok @ErikWittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @IvanGoncharov

Also, please note the scheduled time. It's the same time as usual in UTC, but some of you may live in timezones that have adjusted for daylight savings. Please note the updated time, and/or provide feedback if we should adjust this for daylight savings to accommodate folks better.

**Comment by sjparsons** [comment]
Update: sorry I got the date wrong. We meet on the last Tuesday of the month -- Mar 24! I corrected the link above.

**Comment by sjparsons** [comment]
See actions from this meeting: https://github.com/APIs-guru/graphql-over-http/issues/76

**Comment by michaelstaib** [comment]
Sorry cannot make it this week
