### ISSUE TITLE
Actions from Mar 24 meeting

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#76]
Based on the meeting today, here's the planned actions we'd like to work on next. If you're tagged here and you feel you cannot meet that commitment, please comment or DM me. Also, if you'd like to get involved on any of these actions just post.

Planned before next meeting:

- [x] Everyone - Review and comment on the test suite PR #75
- [ ] @sjparsons - Respond to discussion, review and comments and merge #75 
- [x] @sjparsons - Raise an issue to discuss if we should or should not require JSON as the serialization format; Also bring to the main GraphQL working group meeting as an agenda item
- [x] @spawnia - Clarify the current spec around status codes
- [x] @benjie  - Investigate the steps to getting a custom content-type: application/graphql+json
- [x] @sjparsons - Provide draft one sentence mission statement; share with the GraphQL working group
- [x] @sjparsons - Report back the state of the project legally migrating to GraphQL foundation
 
See [agenda](https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-03-24.md) for notes and more details.

**Comment by benjie** [comment]
General concensus from Spec WG on the content-type is "don't bother getting it approved... yet". Just use it. You can tick that off, I'll be updating people at the next HTTP WG - see #78

**Comment by sjparsons** [comment]
I've used the following mission statement and shared with some leaders at GraphQL Foundation and asked about the process of legally migrating this into the GraphQL Foundation.

> Provide a specification that allows GraphQL clients and servers with different implementations and technology stacks to interact freely over HTTP if both client and server are compliant

Will report what I hear back on that thread at the meeting on Tuesday, April 28.

**Comment by sjparsons** [comment]
I've drafted a PR that adds guidance around serialization format and content-type into the specification. This reflects some ideas that were surfaced in our last meeting and puts inserts into the spec our proposed content type, `application/graphql+json`. 

https://github.com/APIs-guru/graphql-over-http/pull/83
