### ISSUE TITLE
April 28 - Working Group

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#82]
Hello, just opening a discussion to remind interested devs about our working group meeting on Tuesday, April 28th. Please see the agenda and open a PR to add yourself:

https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-04-28.md

@abernix @balshor @benjie @deinok @ErikWittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @IvanGoncharov

**Comment by spawnia** [comment]
Excited for this one, it's going to be a great discussion.

**Comment by michaelstaib** [comment]
I am in.
