### ISSUE TITLE
Would spec also focus on subscriptions?

### ISSUE THREAD

**Issue by wtrocki** [APIs-guru/graphql-over-http#92]
Subscriptions are usually handled over the websockets but they could also utilize http protocol in situations like:

- HTTPS connection update using SNI
- Long polling like implementations

Would the working group consider extending graphql-over-http to include subscriptions over WebSockets ?

**Comment by sjparsons** [comment]
Hi @wtrocki, 

At this point we are focussing on getting a 1.0 release done, so I don't think we would consider it immediately. You can see our [Roadmap](https://github.com/APIs-guru/graphql-over-http/blob/master/ROADMAP.md#version-10) to get insight to what we envision should be in the 1.0 release. However, after the 1.0 release, it's something that we would be willing to consider.

**Comment by wtrocki** [comment]
Makes sense

**Comment by benjie** [comment]
@wtrocki I think you meant "long polling" rather than "long pooling", please could you edit?

**Comment by wtrocki** [comment]
Done

**Comment by sjparsons** [comment]
I'm going to close this issue for now, since I think the question has been answered. Will plan to answer more questions and entertain topics at the working group on this after the 1.0 release.
