### ISSUE TITLE
Actions from 24 April 2020 meeting

### ISSUE THREAD

**Issue by sjparsons** [APIs-guru/graphql-over-http#96]
Sorry, I'm a bit late in posting this... Based on the [24 April 2020 working meeting](https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-04-28.md), here's the planned actions we'd like to work on next. If you're tagged here and you feel you cannot meet that commitment, please comment or DM me. Also, if you'd like to get involved on any of these actions just post.

Planned before next meeting:

- [ ] @sjparsons Research some other serialization formats and whether they have implications for content-types / status codes. 
- [x] @sjparsons Merge proposed automated tests https://github.com/APIs-guru/graphql-over-http/pull/75
- [ ] @jaydenseric (pending above) Implement some of the automated tests in: https://github.com/jaydenseric/graphql-http-test
- [ ] @michaelstaib How many other people are using `application/graphql` as a common format instead of `application/graphql+json` for submitting requests. GitHub? Shopify? Braintree (@sjparsons can look into this) How popular is it?
- [ ] @sjparsons How can the server recognize the client sent a GraphQL Request? Clarify that part in the spec.

**Comment by sjparsons** [comment]
@jaydenseric I merged https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/test-suite.md so that should unblock you, though I know there's not much time before next meeting.

**Comment by sjparsons** [comment]
Closing in preference of https://github.com/APIs-guru/graphql-over-http/issues/103

**Comment by michaelstaib** [comment]
@sjparsons I have reached out to marc from GitHub and am waiting for his response. I also read into the docu of GitHub and it seems that they only use a JSON structure for their request:
https://developer.github.com/v4/guides/forming-calls/#the-graphql-endpoint

But let's wait for his response.
